
<div class="list-filters">
    <div class="filter-align-left">
        <div class="filter-align-left input-opentext input-group ">
            <input type="text" class="form-control " placeholder="search">
            <span class="input-group-btn">
                <button class="btn btn-default" type="button"><span class="glyphicon glyphicon-search"></span</button>
            </span>
        </div>
    </div>
    <div class="filter-align-left">
        <div class="btn-group ">
            <button type="button" class="btn btn-default input-ddsection">Section</button>
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                <span class="caret"></span>
                <span class="sr-only">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li><a href="#">Mi cuerpo</a></li>
                <li><a href="#">Mis hijos</a></li>
                <li><a href="#">Mi casa</a></li>
                <li><a href="#">Mi ciudad</a></li>
                <li><a href="#">Mi mundo</a></li>
            </ul>
        </div>

    </div>
    <div class="clearfix"></div>
</div>

<div class="list-container">

    <table class="table table-hover">

        <thead>
            <tr>
                <th></th>
                <th>Title</th>
                <th>Section</th>
                <th class="list-cell-align-center">Publish date</th>
                <th class="list-cell-align-center">Views</th>
                <th class="list-cell-align-center">Shares</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="list-cell-align-center "><a href=""><span class="glyphicon glyphicon-ok-circle  list-status-publish-on"></span></a></td>
                <td class="list-cell-title">Antes de ir a Ikea</td>
                <td>Mi casa</td>
                <td class="list-cell-align-center">02.10.2014</td>
                <td class="list-cell-align-center">33</td>
                <td class="list-cell-align-center">6</td>
                <td>
                    <a href=""><span class="glyphicon glyphicon-eye-open list-action-button"></span></a>&nbsp;&nbsp;
                    <a href=""><span class="glyphicon glyphicon-pencil list-action-button"></span></a>&nbsp;&nbsp;
                    <a href=""><span class="glyphicon glyphicon-trash list-action-button"></span></a>

                </td>
            </tr>
            
            <tr>
                <td class="list-cell-align-center "><a href=""><span class="glyphicon glyphicon-remove-circle  list-status-publish-off"></span></a></td>
                <td class="list-cell-title">Como tomar medidas de una habitacion?</td>
                <td>Mi casa</td>
                <td class="list-cell-align-center">02.10.2014</td>
                <td class="list-cell-align-center">33</td>
                <td class="list-cell-align-center">6</td>
                <td>
                    <a href=""><span class="glyphicon glyphicon-eye-open list-action-button "></span></a>&nbsp;&nbsp;
                    <a href=""><span class="glyphicon glyphicon-pencil list-action-button "></span></a>&nbsp;&nbsp;
                    <a href=""><span class="glyphicon glyphicon-trash list-action-button "></span></a>

                </td>
            </tr>
            
            <tr>
                <td class="list-cell-align-center "><a href=""><span class="glyphicon glyphicon-ok-circle  list-status-publish-on"></span></a></td>
                <td class="list-cell-title">Materiales saludables para tu casa</td>
                <td>Mi cuerpo</td>
                <td class="list-cell-align-center">02.10.2014</td>
                <td class="list-cell-align-center">33</td>
                <td class="list-cell-align-center">6</td>
                <td>
                    <a href=""><span class="glyphicon glyphicon-eye-open list-action-button"></span></a>&nbsp;&nbsp;
                    <a href=""><span class="glyphicon glyphicon-pencil list-action-button"></span></a>&nbsp;&nbsp;
                    <a href=""><span class="glyphicon glyphicon-trash list-action-button"></span></a>

                </td>
            </tr>
            
            
            <tr>
                <td class="list-cell-align-center "><a href=""><span class="glyphicon glyphicon-remove-circle  list-status-publish-off"></span></a></td>
                <td class="list-cell-title">A quien tengo que llamar para hacer lo que no puedo hacer yo?</td>
                <td>Mi casa</td>
                <td class="list-cell-align-center">02.10.2014</td>
                <td class="list-cell-align-center">33</td>
                <td class="list-cell-align-center">6</td>
                <td>
                    <a href=""><span class="glyphicon glyphicon-eye-open list-action-button"></span></a>&nbsp;&nbsp;
                    <a href=""><span class="glyphicon glyphicon-pencil list-action-button"></span></a>&nbsp;&nbsp;
                    <a href=""><span class="glyphicon glyphicon-trash list-action-button"></span></a>

                </td>
            </tr>
            <tr>
                <td class="list-cell-align-center "><a href=""><span class="glyphicon glyphicon-ok-circle list-status-publish-pending"></span></a></td>
                <td class="list-cell-title">Dónde meto a las visitas?</td>
                <td>Mi casa</td>
                <td class="list-cell-align-center">02.10.2014</td>
                <td class="list-cell-align-center">33</td>
                <td class="list-cell-align-center">6</td>
                <td>
                    <a href=""><span class="glyphicon glyphicon-eye-open list-action-button"></span></a>&nbsp;&nbsp;
                    <a href=""><span class="glyphicon glyphicon-pencil list-action-button"></span></a>&nbsp;&nbsp;
                    <a href=""><span class="glyphicon glyphicon-trash list-action-button"></span></a>

                </td>
            </tr>
            
            <tr>
                <td class="list-cell-align-center "><a href=""><span class="glyphicon glyphicon-ok-circle  list-status-publish-on"></span></a></td>
                <td class="list-cell-title">Seguridad infantil y accidentes en casa</td>
                <td>Mis hijos</td>
                <td class="list-cell-align-center">02.10.2014</td>
                <td class="list-cell-align-center">33</td>
                <td class="list-cell-align-center">6</td>
                <td>
                    <a href=""><span class="glyphicon glyphicon-eye-open list-action-button"></span></a>&nbsp;&nbsp;
                    <a href=""><span class="glyphicon glyphicon-pencil list-action-button"></span></a>&nbsp;&nbsp;
                    <a href=""><span class="glyphicon glyphicon-trash list-action-button"></span></a>

                </td>
            </tr>
            <tr>
                <td class="list-cell-align-center "><a href=""><span class="glyphicon glyphicon-ok-circle  list-status-publish-pending"></span></a></td>
                <td class="list-cell-title">Las nuevas ciudades inteligentes</td>
                <td>Mi ciudad</td>
                <td class="list-cell-align-center">02.10.2014</td>
                <td class="list-cell-align-center">33</td>
                <td class="list-cell-align-center">6</td>
                <td>
                    <a href=""><span class="glyphicon glyphicon-eye-open list-action-button"></span></a>&nbsp;&nbsp;
                    <a href=""><span class="glyphicon glyphicon-pencil list-action-button"></span></a>&nbsp;&nbsp;
                    <a href=""><span class="glyphicon glyphicon-trash list-action-button"></span></a>

                </td>
            </tr>
                       
            
            
            
        </tbody>

    </table>
    <div class="list-additem">
        <a href=""><span class="glyphicon glyphicon-plus-sign"></span>Add new article</a>        
    </div>

</div>


<div class="list-pagination">
    
    <ul class="pagination">
        <li><a href="#">&laquo;</a></li>
        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
        <li><a href="#">&raquo;</a></li>
    </ul>


</div>
