<div class="list-filters">
        
        
        <div class="filter-align-left">
            <div class="filter-align-left input-opentext input-group ">
                <input type="text" class="form-control " placeholder="search" id="searchInput" value="<?= $this->filters['text'] ?>">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button" id="searchButton"><span class="glyphicon glyphicon-search"></span</button>
                </span>
                
            </div>
        </div>
        <div class="filter-align-left">
            <div class="btn-group ">
                <?php 
                    $section_list = '';
                    $selectedSection = '';
                    foreach ($this->sections as $section) {
                        $active = '';
                        if (!empty($this->filters['section_id'])) {
                            if ($this->filters['section_id']==$section->id) {
                                $selectedSection = $section->name;
                                $active = 'class="active"';
                            }
                        }   
                        $section_list  .= "<li $active> <a href=\"#\" data-value=\"$section->id\" >$section->name</a></li>";
                    }

                    if ($selectedSection!='') {
                        echo "<button type=\"button\" class=\"btn btn-default input-ddsection\">$selectedSection</button>";
                    }else {
                        echo '<button type="button" class="btn btn-default input-ddsection dropdown-unselected">Section</button>';
                    }
                ?>
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    <span class="caret"></span>
                    <span class="sr-only">Toggle Dropdown</span>
                </button>
                <ul class="dropdown-menu" role="menu" id="sectionDropDown">
                    <li > <a href="#" data-value="-1" >All</a></li>
                    <?= $section_list;?>
                </ul>
            </div>

        </div>
        <div class="clearfix"></div>
    </div>

    
    
    
    <div class="list-container">

        <table class="table table-hover">

            <thead>
                <tr>
                    <th></th>
                    <th>Title</th>
                    <th>Section</th>
                    <th class="list-cell-align-center">Publish date</th>
                    <th class="list-cell-align-center">Views</th>
                    <th class="list-cell-align-center">Shares</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>

                 <?= $this->partialLoop('_articles_list_item.phtml',$this->results); ?>

            </tbody>

        </table>
        <div class="list-additem">
            <a class="newContentButton"><span class="glyphicon glyphicon-plus-sign"></span>Add new article</a>
        </div>

    </div>

    <div class="list-pagination">

    <?= $this->paginationControl($this->results,
                                                    'Sliding',
                                                    '_pagination.phtml'); ?>

    </div>