
<div class="list-filters">


    <div class="filter-align-left">
        <div class="filter-align-left input-opentext input-group ">
            <input type="text" class="form-control " placeholder="search" id="searchInput" value="<?= $this->filters['text'] ?>">
            <span class="input-group-btn">
                <button class="btn btn-default" type="button" id="searchButton"><span class="glyphicon glyphicon-search"></span</button>
            </span>

        </div>
    </div>

    <div class="clearfix"></div>
</div>




<div class="list-container">

    <table class="table table-hover">

        <thead>
            <tr>
                <th></th>
                <th>Title</th>
                <th class="list-cell-align-center">Publish date</th>
                <th class="list-cell-align-center">Views</th>
                <th class="list-cell-align-center">Shares</th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            <?= $this->partialLoop('_diapos_list_item.phtml', $this->results); ?>

        </tbody>

    </table>
    <div class="list-additem">
        <a class="newContentButton"><span class="glyphicon glyphicon-plus-sign"></span>Add new diapo</a>
    </div>

</div>

<div class="list-pagination">

    <?=
    $this->paginationControl($this->results, 'Sliding', '_pagination.phtml');
    ?>

</div>