
<?php if ($this->pageCount>1): ?>
    <ul class="pagination">
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <li><a href="#" onclick="mainView.loadPage('<?= $this->previous; ?>')">&laquo;</a></li>
        <?php else: ?>
            <li class="disabled"><a href="#">&laquo;</a></li>
        <?php endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <li><a href="#" onclick="mainView.loadPage('<?= $page; ?>')" ><?php echo $page; ?></a></li>
            <?php else: ?>

                <li class="active"><a href="#"><?= $page; ?></a></li>
            <?php endif; ?>
        <?php endforeach; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
            <li><a href="#" onclick="mainView.loadPage('<?= $this->next; ?>')" >&raquo;</a></li>
        <?php else: ?>
            <li class="disabled"><a href="#">&raquo;</a></li>
            <?php endif; ?>
    </ul>
<?php endif; ?>