
<span class="btn btn-success fileinput-button">
    <i class="glyphicon glyphicon-plus"></i>
    <span>Add files...</span>
    <input type="file" name="files[]" multiple="">
</span>
<div id="progress" class="progress">
        <div class="progress-bar progress-bar-success"></div>
    </div>
    <!-- The container for the uploaded files -->
    <div id="files" class="files"></div>

<div class="form-group has-feedback">
    <label for="inputTitle">Title</label>
    <input type="text" class="form-control" id="newContentTitleInput" placeholder="Please enter content title" value="">
</div>
<link rel="stylesheet" href="fileupload/css/jquery.fileupload.css">

<script src="/js/libs/jquery.fileupload/jquery.iframe-transport.js"></script>
<script src="/js/libs/jquery.fileupload/jquery.fileupload.js"></script>
<script src="/js/libs/jquery.fileupload/jquery.fileupload-ui.js"></script>

<script src="/js/views/popup-newcontent-view.js"></script>

<script>

    var newContentModalView;
    
    function showNewContentController() {
        
        
        contentModel = new ContentModel({ 
            title: '',
            popuptitle: '<?php echo $this->popuptitle; ?>'
        });
         
        newContentModalView = new NewContentPopupView({
             model: contentModel,
             el: $('#newContent_popup')
             
        });
        
        
        newContentModalView.on("success",function() {
            if (contentModel.get('id')) {
                mainView.clearModals();
                urlModel.saveURL();
                mainView.loadDynamicContent('/edit/id/'+contentModel.get('id'));
            }
        });
        newContentModalView.showPopup();
    }
    
</script>




<script>
/*jslint unparam: true */
/*global window, $ */
$(function () {
    'use strict';
    // Change this to the location of your server-side upload handler:
    var url = window.location.hostname === 'http://localamcadmin' ?
                '//jquery-file-upload.appspot.com/' : 'uploads/';
    $('#fileupload').fileupload({
        url: url,
        dataType: 'json',
        done: function (e, data) {
            $.each(data.result.files, function (index, file) {
                $('<p/>').text(file.name).appendTo('#files');
            });
        },
        progressall: function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $('#progress .progress-bar').css(
                'width',
                progress + '%'
            );
        }
    }).prop('disabled', !$.support.fileInput)
        .parent().addClass($.support.fileInput ? undefined : 'disabled');
});
</script>